const perception = {
    "visual-spatial": {
        "definition": "the human ability to think in images and pictures--the capacity to visualize accurately and abstractly",
        "music": "drawing diagrams, making collages, taking photos, puzzles, playing sports, using maps"
    },

    "logical-mathematical": {
        "definition": "the human ability to think in images and pictures--the capacity to visualize accurately and abstractly",
        "music": "programming, building systems, observing patterns in nature, writing mysteries, music composition"
    },
    
    "supervised": {
        "definition": "the computational ability to predict outcomes and recognize patterns from data sets organized and labeled by humans",
        "music": "the computational ability to predict outcomes and recognize patterns from data sets organized and labeled by humans"
    },
    "unsupervised": {
        "definition": "the computational ability to predict outcomes and recognize patterns from raw and unorganized data points generated by human activity",
        "music": "finding shapes in clouds, playing with a kaleidoscope, summarizing a story, connecting stars to constellations"
    },  
 };


