const perceptions = {
    "visual-spatial": {
        "styleIcon": "visual-spatial.jpg",
        "styleDefinition": "the human ability to think in images and pictures--the capacity to visualize accurately and abstractly"
    },

    "logical-mathematical": {
        "styleIcon": "logical-mathematical.jpg",
        "styleDefinition": "the human ability to think in images and pictures--the capacity to visualize accurately and abstractly"
    },
    
    "supervised": {
        "styleIcon": "supervised.jpg",
        "styleDefinition": "the computational ability to predict outcomes and recognize patterns from data sets organized and labeled by humans"
    },
    "unsupervised": {
        "styleIcon": "unsupervised.jpg",
        "styleDefinition": "the computational ability to predict outcomes and recognize patterns from raw and unorganized data points generated by human activity"
    },  
 };


