const perception = {
    "visual-spatial": {
        "styleDefinition": "the human ability to think in images and pictures--the capacity to visualize accurately and abstractly"
    },

    "logical-mathematical": {
        "styleDefinition": "the human ability to think in images and pictures--the capacity to visualize accurately and abstractly"
    },
    
    "supervised": {
        "styleDefinition": "the computational ability to predict outcomes and recognize patterns from data sets organized and labeled by humans"
    },
    "unsupervised": {
        "styleDefinition": "the computational ability to predict outcomes and recognize patterns from raw and unorganized data points generated by human activity"
    },  
 };


